from django.urls import path
from . import views

urlpatterns = [
    path('config/', views.config),
    path('config', views.config),
    path('register/', views.register),
    path('register', views.register),
    path('login/', views.login),
    path('login', views.login),
    path('refresh/', views.refresh_token),
    path('refresh', views.refresh_token),
    path('doctors/', views.get_doctors),
    path('doctors', views.get_doctors),
    path('doctors/<int:doctor_id>/', views.get_doctor_by_id),
    path('doctors/<int:doctor_id>', views.get_doctor_by_id),
    path('predictions/', views.get_predictions),
    path('predictions', views.get_predictions),
    path('appointments/', views.get_appointments),
    path('appointments', views.get_appointments),
    path('messages/', views.get_messages),
    path('messages', views.get_messages),
    path('reports/', views.get_reports),
    path('reports', views.get_reports),
    path('reports/generate/', views.generate_report),
    path('reports/generate', views.generate_report),
    path('appointments/request/', views.create_appointment),
    path('appointments/request', views.create_appointment),
    path('appointments/<int:appointment_id>/cancel/', views.cancel_appointment),
    path('appointments/<int:appointment_id>/cancel', views.cancel_appointment),
    path('appointments/<int:appointment_id>/confirm/', views.confirm_appointment),
    path('appointments/<int:appointment_id>/confirm', views.confirm_appointment),
    path('appointments/<int:appointment_id>/status/', views.update_appointment_status),
    path('appointments/<int:appointment_id>/status', views.update_appointment_status),
    path('conversations/', views.get_conversations),
    path('patient/profile/', views.upsert_patient_profile),
    path('patient/profile', views.upsert_patient_profile),
    path('conversations', views.get_conversations),
    path('messages/send/', views.send_message),
    path('messages/send', views.send_message),
]